### ISSUE TITLE
Examples in the front page

### ISSUE THREAD

**Issue by rusosnith** [mysociety/yournextrepresentative#155]
For foreigners looking into the project (probably to use it in other countries) would be great to have a frew candidates examples to look at (looking it up is a no go, we don't know any names)

It may be a random candidate?

**Comment by zarino** [comment]
This is a good idea.

Candidates are currently accessible either by navigating to "Constituencies" in the nav bar, and then picking a constituency, or by clicking one of the "a new candidate" or "candidate #12345" links in the "Recent changes" section of the homepage:

![screen shot 2015-01-21 at 14 04 45](https://cloud.githubusercontent.com/assets/739624/5837363/84169216-a176-11e4-84d0-59005b44111c.png)

I wonder whether we could kill two birds with one stone by making that "Recent changes" view better (showing candidates’ names rather than ID numbers)?

**Comment by tmtmtmtm** [comment]
Perhaps closed by #621?

**Comment by tmtmtmtm** [comment]
Ooops. I meant to just leave that as a comment, but as 621 implies that it probably _was_ closing this, I'm going to leave this as closed and we can re-open if it's still a problem.
