### ISSUE TITLE
Images are wrongly cached on web page after being removed

### ISSUE THREAD

**Issue by jarofgreen** [mysociety/yournextrepresentative#313]
Why does Helen have a picture here https://yournextmp.com/person/7325/helen-spiby-vann but not here http://yournextmp.popit.mysociety.org/api/v0.1/persons/7325 ? 
Thanks

**Comment by andylolz** [comment]
Yeah, I think it’s caching. I removed the photo(s) of Helen yesterday (because she emailed and asked us to, due to the colour problems)

**Comment by jarofgreen** [comment]
Can this issue become then "remove cache image from https://yournextmp.com/person/7325/helen-spiby-vann page that should not be there"

**Comment by mhl** [comment]
The cached image is still being shown because @andylolz deleted them in PopIt (the only way to do that at the moment) but YourNextMP doesn't know that that's happened (see https://github.com/mysociety/popit/issues/818). Staff users have an "invalidate cache" button on the person and constituency pages for dealing with this, but since the current image is probably OK, I wouldn't click it yet.

**Comment by jarofgreen** [comment]
She now appears on https://yournextmp.com/constituency/65883/hornsey-and-wood-green

But not https://yournextmp.com/person/7325/helen-spiby-vann

And not in JSON.

**Comment by mhl** [comment]
That's because the person cache was invalidated, but not the posts cache.

**Comment by mhl** [comment]
We've removed the caching of person and post data now, so this is no longer relevant.

**Comment by andylolz** [comment]
Hooray!!! :tada:
