### ISSUE TITLE
mark up strings on the site for translation

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#353]
See:
- https://docs.djangoproject.com/en/1.7/topics/i18n/translation/

Obviously that won't be enough to localize the site for Argentina, but it's a necessary pre-requisite. Some care will be needed to make sure that format strings make sense in isolation e.g. `"Information about {full_name}"` rather than `"Information about {0}"`

**Comment by martinszy** [comment]
I started this, but I can't get the site to take the strings from the po/mo files.
https://github.com/YoQuieroSaber/yournextmp-popit

I've also created a document in the wiki commenting on the process I followed: 
https://github.com/YoQuieroSaber/yournextmp-popit/wiki/Translation-process

**Comment by dracos** [comment]
I have successfully viewed the site with your Spanish translations :) I have uploaded the translation to Transifex which you can find at https://www.transifex.com/projects/p/yournextmp/ , in case that's a preferable way of translating. Or you can edit the .po file in locale/es_AR directly as you have done in your fork. I think one issue you had was that you want a LANGUAGE_CODE of `es-ar`, not `es_AR`. I have added code to our branch to allow you to set a default fallback language/timezone in the `general.yml` file rather than settings.

As you say in your wiki, you can run `compilemessages` when you add translations; the other steps should all have been done for you now on our master branch.

**Comment by JenMysoc** [comment]
A string on the Email confirmation page is untranslatable still:

"We have sent an e-mail to you for verification. Follow the link provided to finalize the signup process. Please contact us if you do not receive it within a few minutes."

**Comment by dracos** [comment]
That's in a third party library (allauth) where the particular translation has been marked as fuzzy. That is fixed in the 0.21 release (we are currently using 0.18), so if an upgrade is possible, that should fix it.

**Comment by mhl** [comment]
@dracos I've updated allauth in [this pull request](https://github.com/mysociety/yournextrepresentative/issues/446) and put it on the staging site, but this message is still coming up in English, even with `es` first in my `Accept-Languages`:

* http://argentina.ynr.staging.mysociety.org/accounts/confirm-email/

Or testing on the command line with:

    curl -H 'Accept-Language: es' 'http://argentina.ynr.staging.mysociety.org/accounts/confirm-email/'

Is there a step I'm missing? (`./manage.py compilemessages` has been run as part of the deploy.)

**Comment by dracos** [comment]
Sigh, the .mo file bundled with allauth is not up to date with the po file: https://github.com/pennersr/django-allauth/tree/master/allauth/locale/es/LC_MESSAGES

If you manually run msgfmt in the right directory of the virtualenv (as I just did to test), it then works fine.

**Comment by dracos** [comment]
Have submitted https://github.com/pennersr/django-allauth/issues/1032

**Comment by mhl** [comment]
The site is translatable now, and new bugs should be opened for missing strings.
