### ISSUE TITLE
How to change document link

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#471]
http://investigacion.yoquierosaber.org/person/2/update

The "guidance on sourcing fields" is linked to a mysociety document.
How do I change it?

**Comment by dracos** [comment]
I left the URL out of the translation string as I thought a translator wouldn't want to translate it – which is fine for a translation of YourNextMP, but not good for a translation that is for another site!
I have put it in the translation in b82fb26db39608bb81f83f485701f90dba3cd2bd, so that a translation can change the URL.
