### ISSUE TITLE
Confusing multiple elections

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextrepresentative#472]
In the candidate page, we have the candidate listed as candidate for all the elections.

Example: http://investigacion.yoquierosaber.org/person/46/emilio-martinez-garbino

Distritos:
Candidato actualmente en Senadores Nacionales PASO 2015
No hay información aún
Candidato actualmente en Presidentes PASO 2015
No hay información aún
Candidato actualmente en Gobernador PASO 2015
No hay información aún
Candidato actualmente en Diputados Nacionales PASO 2015
Diputado Nacional por ENTRE RIOS Frente Entrerriano Federal para el Trabajo, la Producción y la Justicia Social

He is actually ever going to be candidate for one of these elections, so it's confusing to list all of them here.

**Comment by mhl** [comment]
This is also bad in the 2016 UK elections, e.g:

![too-many-elections](https://cloud.githubusercontent.com/assets/7907/11894408/c3d751fe-a56e-11e5-880b-b8efa8c6e431.png)

**Comment by tfgg** [comment]
It'll also get much worse if we add local elections. In the UK, though, I'm not sure if it's technically true that someone can't stand in multiple elections - it might even be a regular occurrence, e.g. a minor candidate standing for MSP also re-running as a councillor.

I guess it just needs a slightly different UX for adding standings, and then there's the semantics of "No information yet" versus "Not standing" that I suspect isn't that important, since if you're not known to be standing you're assumed to not be, and might actually introduce errors if someone is marked as not standing but actually stands in another constituency.

**Comment by mhl** [comment]
Yeah, we definitely still want to allow people to stand in multiple constituencies; I'm thinking more of just hiding the "not standing" and "no information yet" elections on the view page, while on the edit page having some Javascript enhancement to hide them unless someone unhides an election in order to add them as a candidate.
