### ISSUE TITLE
take the site name from the sites framework, not localised strings

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#506]
At the moment, if you view `https://edit.yournextmp.com` with `es` first in your `Accept-Language` header, you'll see the site in Spanish, but its name will shown as "Yo Quiero Saber" rather than "YourNextMP". To fix this, I think that uses of the site name in translated strings should come from an interpolated variable which is taken from the name set in the [sites framework](https://docs.djangoproject.com/en/1.8/ref/contrib/sites/).

**Comment by martinszy** [comment]
A related issue.

For instance, in this page:
http://investigacion.yoquierosaber.org/help/privacy

With the browser in English you get the message:
"This site is run by Democracy Club."

And in Spanish you get:
"Este sitio es posible gracias a la colaboración de Congreso Interactivo, OpenKnowledge Argentina, Taringa, HacksLabs, We-Me y muchos voluntarios como vos."

Since this strings represent different partnerships to run de site in different countries, they should not be dependent entirely on the translations.
Or maybe there should be some translated strings per-election.
