### ISSUE TITLE
extend django-popolo models and subclass popit importer to populate them

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#553]

**Comment by mhl** [comment]
Work-in-progress here: https://github.com/mysociety/yournextrepresentative/compare/move_elections_to_model...popolo-import-wip?expand=1

**Comment by struan** [comment]
I'm just going to note that I tried this just now on a Burkina Faso export from my dev instance and it fell over because the Organization object didn't have a slug_source property. This seems to be something caused by the overriding of the get_popolo_model method but I don't really understand the migration magic well enough to understand what is happening there.

**Comment by mhl** [comment]
Done in 9e632089cc38cff5eac829
