### ISSUE TITLE
write a blog post about having removed PopIt from YNR

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#571]

**Comment by tmtmtmtm** [comment]
Live at http://longair.net/blog/2016/02/15/migrating-yournextrepresentative-from-popit-to-django-popolo/
and https://www.mysociety.org/2016/02/17/unpicking-code-for-the-good-of-the-project/

**Comment by wfdd** [comment]
I saw this the other day - it might've been on the Poplus mailing list?  Anyway, thanks for the write-up.  It sounds like it was the dated architecture of PopIt that was the principal reason for its abandonment, and there does appear to remain demand for a general-purpose politician store (see [popit_ng](https://github.com/Sinar/popit_ng) and #697).

**Comment by tmtmtmtm** [comment]
@wfdd — I certainly agree that people would _like_ a general-purpose politician store, but I'm extremely sceptical that such a thing is possible — at least not in most of the ways that I've seen to date.
I think the fundamental problem with PopIt in this regard wasn't really a dated architecture, but a fatal flaw in its core purpose. Effectively it was something akin to phpMyAdmin — a web-based tool that let you construct arbitrary entities, and relationships between them, and then query and display those. But just as you can't write generic queries that will be able to run against anyone else's SQL database, without first knowing how they've modelled their data (because everyone will end up using different approaches to express the same things), so you couldn't ever use someone else's PopIt data without first puzzling out what way they'd arranged things. For the vast majority of individual users, this wasn't a problem. They were only wanting to read the data that they themselves had created. They knew the structure, so wrote code to query that, just as millions of people the world over quite happily write code every day that interrogates their own SQL database. 

But one of the goals of PopIt was that you shouldn't need to know anything about the underlying structure of the data in an instance to be able to use it — it should be the same everywhere. Effectively it did this by equivalent of constraining the table names and column names you could use, on the assumption that if everyone standardised on _those_, then it would easy (or at least possible) to write code that can read the data from any instance. 

This, however, turned to be entirely false. The very nature of how you express relationships between People and Organizations through Memberships and Posts is very flexible, but essentially just pushes the problem back a level. Now the important information lives in unconstrained text fields, that are again impossible to read without knowing what choices someone made. As before, you're back to being able to fairly easily write one-off code to read from a single instance, but with no ability to write code to read from _all_ instances.


To give a concrete example: let's say you need a list of all the current and former Finance Minsters across the EU countries (and assume for now that a group in each Member State has actually created a PopIt that actually contains rich enough information for this).

But unless all of those groups have arranged in advance exactly how to model this sort of data (and actually stuck to it), you're almost certainly in for a world of pain. The chances that this information is constructed in the same way across every instance is effectively zero. In fact you're probably going to find that even different people holding that position in a single country are likely to be entered in different ways within the same instance, unless the admins for it were much more rigorous than the vast majority I've seen (and I spent several months last year examining quite deeply every PopIt that I could find). 


Even if we assume that everyone has their data in English (which of course they won't), you'll likely find that in one country you're looking for a role of "Minister of Finance"; in another it'll be "Federal Minister of Finance"; in another "Finance Minister"; in another "Minister of Economy and Finance", etc. Then you discover that some of the PopIts include so much information that there are multiple simultaneous Finance Ministers within them. Aha, you discover after a puzzled half-hour of investigation, the UK one also includes the devolved executives of Scotland, Northern Ireland, and Wales as well! But you don't want to include those — so you need to look at what Organization the Position is held at as well. And now you discover even more inconsistency — not just in how people have named the concept, but in what they think the concept even is. One has the Organization as "Cabinet". Several just have "Government" (though one has that in lower case, and one managed to mis-spell it as "Goverment"). One has "Welsh Government". One has separate Organisations for "Cameron's First Ministry", "Cameron's Second Ministry", etc. One just has "Malta". And then you notice that several others have variations on just having them be "Minister" (or "Federal Minister", etc) at an organisation "Ministry of Finance".

The groups who constructed each of these PopIts haven't done anything odd. They've modelled things in a way that makes perfect sense to them, and have no difficulty at all in writing the scripts that read the data back out and process it. But someone needing to read the data from 28 different PopIts needs to spend significant time looking at each in turn to see how they've expressed things, and fill their code with dozens of special case queries — defeating the entire wider goal of what PopIt was trying to avoid. 

And this is just for one query looking at a single position.

Once you get into more complex queries (for example "Across each national parliament, do more people change political allegiance in the first half of their term or the second half?") you're discovering that PopIt's structures not only don't help you, but are actively making it _harder_ to get the data you need.

I currently only know two approaches that might (just might!) be able to solve this sort of thing.

The first is to very very tightly control what people can enter — e.g. saying the legislative memberships *must* be entered like _this_; cabinet members like _this_, etc; and providing no ability for people to deviate from that. Any time someone wants to add a new category of information, the software needs to adapt to work out how to ensure that that can be entered in a way that's flexible enough to work in every country, and yet constrained enough to be able to be expressed in a consistent manner.

The other is to allow the flexibility on what can be entered in individual fields, but to enforce that everything is within a hierarchy of data that eventually resolves to something sufficiently standard (e.g that no matter how someone enters the Minister of Finance, that all the posts/roles/organizations etc are instances of things that end up saying that you're dealing with a Minister, with responsibility for Finance, within a Cabinet, of the National Executive, of a Country (probably involving quite a deep hierarchy for each of those things). Now, whenever you want a new category of information, you still need to do lots of preparation work — but by creating data hierarchies rather than software. 

Both are a lot of work — but I firmly believe that that's where the trade-off is always going to lie. You can either make the data easy to _create_, or easy to _query_ — never both. The question is where along that line you want to lie, and how much can you push each of those things out of the application and into various standards.

Conceptually I believe the second approach is better. But in practice I've only ever met a handful of groups who could adequately model their data like this, as it involves not only a really deep understanding of how exactly how every relevant part of their own country's government is formed and how all the parts of that hang together, but also how that compares to other places, and what the commonalities and differences are. And the overlap between people who know that sort of thing, and who also understand the technical intricacies of data modelling is generally quite slim. And, worse, the sort of people who _do_ understand all the nuances tend to be really bad at finding ways of hiding it all again, so that the vast majority of people who _don't_ understand it could actually use the information without needing a PhD level civics course first.

I believe Wikidata may well manage to solve this, essentially by throwing millions of people at it, having them all clean up each other's data and gradually evolve it towards something consistent. I strongly suspect that this sort of 'slow consensus' will probably work out well in the end, but it's a fairly long term bet, is likely to hit quite a lot of bumps and go down a few dead-ends along the way, and only works with a critical mass of enough community of editors from all over the world (i.e. something that most other tools are unlikely to get.) 

In the meantime, over on EveryPolitician we're taking the first approach, but trying to find as many ways as possible to benefit from what consensus does evolve out of the second on Wikidata.

**Comment by wfdd** [comment]
Thanks for sharing your thoughts, and I'm sorry for not having made time for writing a proper response.

**Comment by tmtmtmtm** [comment]
No worries @wfdd — feel free to drop in any drive-by thoughts you have at any time. Or if you'd like me to put it some somewhere like Medium, where you have line-by-line commenting, I'd be happy to do that too.

**Comment by akuckartz** [comment]
@tmtmtmtm Most of the difficulties you describe in detail can be solved (or avoided) by using semantic web technologies / linked data.

**Comment by tfgg** [comment]
@akuckartz My interpretation is that most difficulties described are _caused_ by semantic/linked data without domain specific interfaces, e.g. a people database being used to store information about politicians.

The issue is that even apparently well-specified standards usually create overly unstructured databases, with an unpredictable modelling mismatch between different groups implementing the same standard, that are difficult to build real-world applications on top of.

As Tony notes, this is solved by having "very very tightly control what people can enter", building non-generalised interfaces that strongly constrain what can be input with a high level of domain experience. The output format can, of course, still be in whatever linked data format you want.

The other solution is "everything is within a hierarchy of data that eventually resolves to something sufficiently standard", which means your semantic / linked data standard has to be superhumanly good at predicting and integrating the domain knowledge in every country in the world. Tony remarks that this is a long-term goal by wiki-esque "slow consensus".

It's not as simple as saying "[use] semantic web technologies / linked data", since that sentence doesn't explain where those data standards and domain knowledge to constrain/create them comes from.

**Comment by akuckartz** [comment]
See also the discussion regarding JSON-LD in #590

**Comment by wfdd** [comment]
JSON-LD isn't a tool for creating vocabularies, ontologies or data specifications.  It's a way to attach metadata alongside your actual data; it's a convenience mechanism.  It can also be used to extend data in an ad hoc manner, e.g. for the purpose of localisation; but knowing the value of property `alpha` is in Greek isn't gonna cure any of your modelling woes.

So, I can't imagine how JSON-LD would be a solution to anything here, though it is very possible that there are things that I'm missing.  Can you clarify?

**Comment by akuckartz** [comment]
@wfdd My link to #590 did not intend to claim that JSON-LD by itself is a solution for the current discussion here.

**Comment by wfdd** [comment]
Right; sorry!
