### ISSUE TITLE
recording winners should work for posts which can have multiple winners

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#582]
At the moment the code assumes that if you mark someone as the winner of an election for a post, everyone else lost, but some posts can have multiple people elected. We should support this (probably adding a property to Election `can_have_multiple_winners`).

**Comment by derekeder** [comment]
:+1: for this!

We ran into this issue for St Paul's elected school board, who are elected at large: http://ynr-st-paul.datamade.us/election/school-board-2015/post/ocd-division,country:us,state:mn,place:st_paul/school-board-member-for-saint-paul

**Comment by tmtmtmtm** [comment]
Rather than `can_have_multiple_winners`, perhaps it would be better to be able to specify a number of winners (ideally on a per-Post basis, though with an election-wide default)? There should be some way of setting this to 'unlimited', but in many cases there'll be a number that can be known in advance.

**Comment by andylolz** [comment]
:+1: for this issue!

Relevant in the UK in 2016 (Welsh Assembly regional elections have multiple winners, for instance)
