### ISSUE TITLE
UK: explore with DemocracyClub what the user journey should be for 2016

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#584]
It would be great to arrange a time with Democracy Club and the design team (@zarino @wrightmartin) to work on how the user journey for YNR for the UK elections in 2016 should work - a postcode will return multiple posts now, which has interesting implications for the usability of the page you're taken to.

Cc: @symroe @tfgg @andylolz

**Comment by zarino** [comment]
Had a chat with Sym and Joe on Friday. Looks like there are going to be 2 separate sites: candidates.democracyclub.org.uk which is a YNR instance for people to crowdsource candidate data, and a separate put-in-your-postcode-see-who-you-can-vote-for site for the general public to use.

**Site 1: Crowdsourcing candidate data**

* Assuming we just use a stock YNR site for this.
* Joe and Sym mentioned some user confusion between the edit and read sites – possibly because they both ask for a postcode first.
* Postcode is *not* the most useful thing to ask editors up front – candidate name is probably better. If the candidate already exists, then they can continue to view/edit them, and if a candidate with that name doesn’t already exist, then they can create one.
* So maybe try swapping out the postcode search on YNR with a "Add or edit a candidate" text input, which autocompletes to existing candidates, with an option at the bottom of the autocomplete dropdown to create a new candidate?
* Joe and Sym not too worried about editors picking the right election/post/area for new candidates – especially since lots of the candidates will either be automatically imported, or added very early on by Joe and Sym anyway.

**Site 2: Who can I vote for**

* Not using YNR frontend for this.
* Homepage search by postcode
* Return a page for *your postcode* (rather than *your constituency* – because the page represents an overlap of potentially 2 or 3 different electoral areas)
* Show on postcode page, in order of importance:
   * The date you need to vote on
   * Where you need to go to vote
      * For most people this will just be "Contact your council [link] to find out"
      * For some it will be "Here's where you vote [map/link]"
      * For the rest it will be "Enter your house number to find out"
   * CTA to "Notify me by email before future elections"
   * The number of posts you can vote for (usually 2 or 3)
   * Colour-coded "polling cards" for each post showing:
      * Title of post (eg: "Police and Crime Commissioner"
      * (in small type) Area the post covers
      * A short paragraph of text explaining what the post *actually does*, with link to Wikipedia article
      * List of known candidates
      * Link to add a new candidate if you know one is missing
   * Below the candidate lists, a final CTA (mostly just a test) for "Not inspired? Stand for election next time" – leads to an email input field?
* Each candidate for each post has a profile page, a bit like the existing YNR ones – name, post, area, and any other data we hold about them. Also, a few CTAs to test:
   * "Support this candidate" (perhaps financially, perhaps in-kind – leads to email input box?)
   * "Correct this data" (leads to candidates.democracyclub.org.uk)
   * "Stand next time" – as before
* Still need pages listing all the candidates by post and by area, so search engines can find them.

![photo 04-03-2016 17 18 30](https://cloud.githubusercontent.com/assets/739624/13565710/ba048268-e449-11e5-8007-cad1208f3b9a.jpg)

![photo 04-03-2016 17 18 46](https://cloud.githubusercontent.com/assets/739624/13565711/bc9bf7ea-e449-11e5-822b-8322c6a63872.jpg)

**Comment by symroe** [comment]
Some lovely guides here might be of interest: http://civicdesign.org/fieldguides/

**Comment by JenMysoc** [comment]
@symroe can we consider this closed?
