### ISSUE TITLE
[placeholder] add email alerts for updates to people (or any people of a particular party)

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#606]
Required for Jamaica.

**Comment by mhl** [comment]
In discussion with @symroe, he said that it might be useful for campaign groups to get alerts by area as well.

**Comment by struan** [comment]
My first thought plan for this is to use the LoggedAction table as the basis of this.

Then add an alerts model, possibly in it's own app, which registers a filter type ( Person, Area, Org ) and possibly a frequency ( daily, hourly ). We then /just/ need a cron job that pulls out the alerts that are due to be sent, pulls a list of relevant actions out the table, munges the versions into a summary, sends out an email and then updates the last_sent date on the alert.

I imagine that initially we don't want to allow everyone to be able to sign up for these so we can just leave the admin interface as the mechanism for updating/creating them.

My concern with this is if there's a lot of these it might be a bit heavy to generate the alerts but I can't see any way round that.

The other option are post save signals that update an alert_due flag on alerts which at least cuts down the amount of polling of the LoggedAction table for alerts that might not be required.

I don't think sending out one email per update is a sensible thing as I can't imagine anyone wants that.

**Comment by symroe** [comment]
I've previously used [Django Notifications](https://github.com/django-notifications/django-notifications) and found it good.  It might be worth investigating for this?

**Comment by struan** [comment]
So, Django notifications looks interesting and gives as a page with a list of updates the person is interested in a la GitHub. We'd still need to implement the emailing part of it and an interface for signing up.

It does mean generating all the notifications at save time as it uses signals to create them which means when a person is saved we need to fetch all the people who want notifications about that and generate them. I'm not sure how efficient this is likely to be but realistically I don't expect we'll have too many people signed up to notifications so it's probably not a disaster.

It does make the email much easier though as it has an emailed flag already so email just become a matter of fetching everything for the person that's not been emailed.

You can also attach data to a notification so we could just include a not about the version change which would make compiling the emails much easier.
