### ISSUE TITLE
Show the winner as the top result for the area page

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/yournextrepresentative#692]
When you go into http://tusrepresentanteslocales.co.cr and pick an alcalde (where the data is there) the winner seems to appear in random order. It would be good if this could be the first result on the page

For example:

![screen shot 2016-02-08 at 09 05 29](https://cloud.githubusercontent.com/assets/4170351/12881679/851ee38e-ce43-11e5-98b5-7caf577b8fc3.png)

and

![screen shot 2016-02-08 at 09 08 38](https://cloud.githubusercontent.com/assets/4170351/12881687/94c0dcac-ce43-11e5-8a8c-c4c4f9b0305c.png)

**Comment by mhl** [comment]
When discussing in estimation we agreed that doing this in the party list case (where the candidates are grouped by party) is much more difficult - we're not sure how to present it, in fact.

So, we're assuming the scope of this ticket is just for `party_lists_in_use=False` elections.

n.b. it would be good to create a ticket to improve the design of the winner highlighting since this was a very rushed job!

**Comment by zarino** [comment]
@mhl Perhaps something super simple like this?

![winner](https://cloud.githubusercontent.com/assets/739624/14822889/49929e92-0bc8-11e6-835a-f86e445fe2a5.jpg)

**Comment by mhl** [comment]
Looks good to me. And I suppose this could be extended fairly easily to the "multiple winners" scenario easily enough by just having multiple people listed in that section.

**Comment by zarino** [comment]
Yep!

**Comment by mhl** [comment]
The yellow might not work with all our site designs, but I guess you'll just make the colour a sass variable anyway?

**Comment by zarino** [comment]
As it happens, those big coloured circle icons are all actual images (because… reasons) – but yes, each theme we create has custom ones made, to match the site colours.

**Comment by wrightmartin** [comment]
👍

**Comment by wfdd** [comment]
- Will this also work with multi-party lists?
- Can we use 'elected' instead of 'winner'? e.g. 'Elected candidate[s] for Alcalde ...'

**Comment by mhl** [comment]
@wfdd Yes, that's not final wording by any means - I don't think "unsuccessful" is a good word to use for people who haven't been elected either.

I think that for party list posts, where there may be zero or more winners from multiple party lists, it would probably be best to have a grouping of everyone elected at the top, then everyone not elected below - within those groups we would group people by party as currently on post pages. Does that sound reasonable to you?

**Comment by wfdd** [comment]
I'm not sure if I like the iconography either to be honest - I don't think of being elected to represent the people as an accomplishment (as the star icon would connote) or even something to be happy about.

That sounds reasonable, yeah.  I suppose within party subpages we'd simply have the non-party list layout?

**Comment by zarino** [comment]
Regarding iconography – On YourNextMP in the UK, last year, we displayed a rosette next to the elected candidates (because rosettes are the traditional thing that "winners" get in the UK, and they're also something candidates are often seen wearing, in the party colours):

![url](https://cloud.githubusercontent.com/assets/739624/14826291/18d13590-0bd5-11e6-97bc-72698fbc94f8.png)

But I expect this doesn't translate very well to other countries!

The other thought I had was a check mark (to mirror the cross we display next to candidates we definitely know aren't standing):

![default icon-winner](https://cloud.githubusercontent.com/assets/739624/14826262/f9c12e9e-0bd4-11e6-8c80-10e5e660c688.png)

But it felt a bit… boring.

Worth remembering also, I guess, that reusers are able to replace these icons in their site's theme directory, so if the default symbol isn't culturally suitable in one country, it can fairly easily be swapped for something else.

**Comment by wfdd** [comment]
Well, I dunno if it's a cultural thing - I think it's more of a personal ideological perspective.  (Actually, I think that we're all undergoing a period of cultural levelling, especially in Europe ... but I digress.)

Yeah, the tick doesn't really click with me.  The star might not be such a bad idea and among other possibilities representative of 'winner' (e.g. a trophy or a medal) it's fairly innocuous.  Would perhaps a swearing an oath hand gesture work?

**Comment by zarino** [comment]
Thanks @wfdd – I’ve had a quick experiment with an icon representing taking an oath, but it's quite a complex concept to represent in a simplified icon like the others. I think we just go ahead with the star for now, and see how other partners react.

**Comment by wfdd** [comment]
Alright, thanks zarino.
