### ISSUE TITLE
Consider UX of party dropdown list

### ISSUE THREAD

**Issue by JoeMitchell** [mysociety/yournextrepresentative#750]
Feedback from DC Group: 

> "Just a thought, but your dropdown list of political parties when adding data for a candidate is really, really unwieldy! It would be a bit more user-friendly if you had basic options for the most common, with a secondary dropdown the others. It also doesn't help that there's seemingly no consistency about which parties have "The" in the front of their name and which don't - I think it would make a lot more sense to  disregard that for sorting purposes."

I think he might not have realised you could start typing. 

![image](https://cloud.githubusercontent.com/assets/8096305/13980364/166a1ad4-f0d6-11e5-8db6-a38c1b0b6837.png)

This may, indeed, not be an issue. But if there was a @zarino or someone good at this sort of thing they might have an idea.

**Comment by zarino** [comment]
Yup, my biggest issue with the default Select2 widget is that it's not clear at all that you can filter the list by typing.

At the very least, a search icon inside the text input would hint that people can type in there to search the list. Some placeholder text like "Type here to filter the list" would be even clearer. I don't think Select2 has any built-in provision for either of these things, but it could probably be monkey-patched in.

Alternatively, you could tell Select2 to construct [Multiple select boxes](https://select2.github.io/examples.html#multiple) rather than exclusive select boxes, which much more clearly look like a thing you can type into, and have a nice autocomplete-style behaviour, which people will be much more used to from search engines and the like. You'd then want to [limit the number of selections to 1](https://select2.github.io/examples.html#multiple-max), so in effect it acts exactly like an exclusive select box again, just with the "type to select" behaviour.

**Comment by tfgg** [comment]
Maybe the most common parties could be put near the top to cover 99% of use cases? It's always a bit annoying having to scroll through all the different Labour parties, or Independent parties to find the correct one.

**Comment by zarino** [comment]
@tfgg – In an ideal world you wouldn't be scrolling anywhere. You'd just type part of the party name, it would be selected in blue, and you'd press enter. And that's what happens right now, except it's easy to miss the hint (flashing cursor) that you can type once you've activated the dropdown box.

(Another reason why maybe styling this more as a "type into this box to see suggestions" widget, rather than a "here's a select menu, which you can also filter", would make it clearer that we're expecting people to type the party name, and we're just going to provide them with an autocomplete once they've given a few letters, rather than making it look like we're expecting them to pick a name from a list, which is absolutely not what we want them do.)

**Comment by tfgg** [comment]
The thing is, even that doesn't work. E.g. typing "labour party" matches more than one party, and the default one isn't the major one.

![image](https://cloud.githubusercontent.com/assets/103349/13987478/a768408c-f0ff-11e5-9036-bc2497d8ca98.png)

**Comment by mhl** [comment]
There was an existing ticket for this here: https://github.com/mysociety/yournextrepresentative/issues/49

The issue that @tmtmtmtm mentioned there is still the blocker for putting the most-frequently-used parties at the top of the list.  At the very least we'd want a different list for posts in Scotland, England, Northern Ireland and Wales. Then there's the issue of how you decide which parties to put in that top list in a neutral way - suggestions welcome for that.

**Comment by zarino** [comment]
A "neutral" way of splitting the well known parties from the less well known ones would probably be to sort the parties by number of existing candidates, and make it clear that's how you're sorting them. Eg:

![screen shot 2016-03-24 at 17 04 06](https://cloud.githubusercontent.com/assets/739624/14024717/7aaacc2a-f1e2-11e5-8872-d702a0f4cac4.png)

Has the advantage that, when you first open the dropdown, the most common parties will be at the top, ordered by the number of candidates we already have registered for them:

![screen shot 2016-03-24 at 17 04 17](https://cloud.githubusercontent.com/assets/739624/14024728/8bf07c8c-f1e2-11e5-8a11-50e17afaa068.png)

**Comment by jf1** [comment]
+1 for Zarino's suggestion. To refine or clarify that, it should only count candidates standing in current elections, but there's no need for the display to mention this.

I hope the devs consider some of these UX issues as 'blockers' even though they're not stopping the code from working or being developed - if a feature is stopping people from contributing then it's stopping the system from working.
