### ISSUE TITLE
Reset password doesn't send the password

### ISSUE THREAD

**Issue by siliconglen** [mysociety/yournextrepresentative#782]
Therefore I can't log in. 

A useful "contact us" in a useful place that's easy to find and has a real email address would also help

**Comment by mhl** [comment]
Sorry to hear you're having problems with this. I just tried a password reset on https://candidates.democracyclub.org.uk/ and got an email - the password reset worked fine. (Sometimes they'll got to people's spam folders, though.)

If you had originally logged in with one of the social login method (e.g. Facebook login, or Twitter login), however, then the password reset option will have no effect, since your account doesn't use a password for logging in. In that case, you've no need for password on the candidates site, and can log back in by clicking on the same option as originally (e.g. Facebook, Twitter, etc.)

The [About page](https://candidates.democracyclub.org.uk/help/about) has a contact email address on it, but I guess some people will search for "Contact us" on a page to find the contact details.

If you're still having problems logging in, please email the email address on that page, so we can discuss this in more detail.

**Comment by siliconglen** [comment]
Click "sign up"
Fill in form: 
Get error "A user is already registered with this e-mail address."
Click "sign in"
Username? Can't remember
Password? Can't remember
Click forgotten password
https://candidates.democracyclub.org.uk/accounts/password/reset/done/
Get feedback "We have sent you an e-mail. Please contact us if you do not receive it within a few minutes."
No email received, no it isn't in the spam folder.

**Comment by siliconglen** [comment]
Can't sign in with twitter
An account already exists with this e-mail address. Please sign in to that account first, then connect your Twitter account.


Can't sign in with Google
An account already exists with this e-mail address. Please sign in to that account first, then connect your Google account.

Oh, I could sign in with Facebook.

That could be *a lot* easier.

**Comment by mhl** [comment]
(I've moved this discussion to email - I hope that's OK.)
