### ISSUE TITLE
allow you to add alternative forms of a candidate's name in the person edit form

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#94]
For example, you could add the variant of their name include middle initials, or use it so that Nicholas Clegg / Nick Clegg will both be found. (Alternative names are supported in PopIt, but we aren't exposing an editing interface for that.)

**Comment by semiprime** [comment]
Adding this here as it's related.

It would be good to be able to select the preferred name from the list of alternative names.

The particular example that's frustrating me at the moment is https://yournextmp.com/person/1043 - the listed name is "Jonny", yet everywhere I can find the name is given as Jonathan (email, homepage, parliament.uk listing, Twitter account, Wikipedia). I don't want to edit the currently listed name since it would presumably end up with the preferred name and the alternative name being Jonathan.

(I guess if you could select the preferred name it would allow people to edit the alternative names too since they could swap the preferred/alternative names, edit the new preferred name, and then swap it back to the alternative name. Whether allowing that is OK is not for me to judge.)

**Comment by tfgg** [comment]
I've fixed that particular case, since it seems that Jonathan is indeed his preferred name. Suggestion sounds sensible, currently you need someone with popit admin privileges. Don't know how high priority it is.

**Comment by mhl** [comment]
Done in https://github.com/mysociety/yournextrepresentative/pull/860
