### ISSUE TITLE
UK: no elections listed when I search a postcode

### ISSUE THREAD

**Issue by Bjwebb** [mysociety/yournextrepresentative#973]
What I did: Type a postcode "CB2 1BY" into the search box.

What I got: Just a list of areas
![image](https://cloud.githubusercontent.com/assets/634/23219779/e22e04b0-f917-11e6-869a-247e1e363bf9.png)

What I expected:
The information on these pages (or links to them):
https://candidates.democracyclub.org.uk/election/local.cambridgeshire.2017-05-04/post/CED:market/market
https://candidates.democracyclub.org.uk/election/mayor.cambridgeshire-and-peterborough.2017-05-04/post/cambridgeshire-and-peterborough/cambridgeshire-and-peterborough-combined-authority

**Comment by jf1** [comment]
I noticed similar when entering M328AA - the only results shown are the [MTW and WMC](https://candidates.democracyclub.org.uk/areas/MTW-gss:E05000836,WMC-gss:E14000979) (not relevant this year) and the results don't show the [GMCA Mayor](https://candidates.democracyclub.org.uk/election/mayor.greater-manchester.2017-05-04/post/greater-manchester/greater-manchester) (a live election).

Additionally, I've just [searched for Manchester](https://candidates.democracyclub.org.uk/search?q=manchester) then Greater Manchester and it only tried to match on candidate names - perhaps first check if the search term matches a high-level Nominatim UK place name?

The only reliable and quick way I've come up with for finding the GM Mayoral election is to enter a candidate name that I already know, but obviously this option isn't available to most people searching for info about candidate names.

**Comment by mhl** [comment]
(Here's a little triage, but I'm only a vaguely aware of how @symroe is handling all these new elections, so this is all a bit superficial.)

That postcode is used for this MapIt query: http://mapit.democracyclub.org.uk/postcode/cb21by

That only returns areas of type: `CED`, `CTY`, `DIS`, `DIW`, `EUR`, `WMC`, `WMP`, `EUP` and `PDG`.

However, the elections you're expecting to be returned have different `AreaType`s associated with them:

* `local.cambridgeshire.2017-05-04` has area types with names `'CED'` and one that I assume is an error since its name is: `''`
* `mayor.cambridgeshire-and-peterborough.2017-05-04` has one area type with name `'combined-authority'`

The only one of those that can work with the code as it ias at the moment is `CED`. That causes a lookup for an area with identifier `unit_id:1277` (formed from `format_code_from_area`) and type `CED`. There's no such `Area`, though - those with type `CED` are: https://gist.github.com/mhl/f04d0930a9b506283adf18438be6a438

So it looks like there might be multiple things going wrong here :(

**Comment by symroe** [comment]
See: utter fury at OS for not making this data open until after the
election.

Also, I plan to use everyelection to do lookups, I've just not got around
to it yet :-\

**Comment by jf1** [comment]
From memory, CEDs aren't straightforward wrt unique identifiers. CAs are, and their boundary data is available [here](http://geoportal.statistics.gov.uk/datasets/0293170f45ac4322868978b46dba822d_4)

**Comment by symroe** [comment]
I've deployed a change to the lookup code in the DC fork that uses our election service to lookup elections. That service has the new boundaries in, so we're able to return results for the missing elections now :)

**Comment by andylolz** [comment]
Looks fixed for the reported postcode:
https://candidates.democracyclub.org.uk/search?q=CB2+1BY

**Comment by mhl** [comment]
I don't know why this says that I reopened this. I suppose I might have clicked "reopen" by accident, but I certainly didn't intend to!
